### ISSUE TITLE
can not render a pdf document when using kableExtra

### ISSUE THREAD

**Issue by MengranLi-git** [cran/kableExtra#1]
My rmarkdown document can not knit to a pdf document, but can render a HTML document. It works well in another computer. If I remove the `library(kableExtra)`, it can also render. But it will keep rendering and finally no response if I use `library(kableExtra)` and want to knit a pdf.

\---
title: "Basic Template"
output: pdf_document
\---

\```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
\```

\```{r libraries, echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE}
library(ggplot2)
library(dplyr)
library(moderndive)
library(gapminder)
library(skimr)
library(kableExtra)
library(gridExtra)
\```

# Introduction {#sec:intro}

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

**Comment by MengranLi-git** [comment]
> Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

The issue has been solved. Some packages of LaTex are not installed, which are applied in the kableExtra package.  If knitting directly, the R will have no response. It would take some time to install and update packages of LaTex. It works to use `kableExtra::kable()` to install packages relied on instead of knitting directly `library(kableExtra)`. And `library(kableExtra)` worked normally after installing the packages.
